Repository leighlars/BreatheAmAIRica, pull requests merged in 2020-09, with the labels that each got.

#8 Feature/jcs header component
  package-lock.json
  package.json
  src/App/App.css
  src/App/App.tsx
  src/Header/Header.tsx
  src/Home/Home.test.tsx
  src/Home/Home.tsx
  src/Search/Search.scss
  src/Search/Search.tsx
  src/View/View.test.tsx
  src/View/View.tsx
Labels: component

#10 Feature/api calls
  src/App/App.tsx
  src/Home/Home.tsx
  src/View/View.tsx
  src/helpers/apiCalls.tsx
Labels: API, component

#11 Feature/crude styling
  public/favicon.ico
  public/globe.png
  public/index.html
  src/App/App.css
  src/App/App.scss
  src/App/App.test.tsx
  src/Header/Header.scss
  src/Header/Header.test.tsx
  src/Header/Header.tsx
  src/Search/Search.scss
  src/Search/Search.test.tsx
  src/Search/Search.tsx
  src/assets/01d.png
  src/assets/01n.png
  src/assets/02d.png
  src/assets/02n.png
  src/assets/03d.png
  src/assets/04d.png
  src/assets/09d.png
  src/assets/10d.png
  src/assets/10n.png
  src/assets/11d.png
  src/assets/13d.png
  src/assets/50d.png
  src/assets/globe.png
  src/index.css
  src/styles/_variables.scss
Labels: UX, component, testing

#21 Feature/top 5 display
  public/manifest.json
  src/App/App.tsx
  src/Location/Location.tsx
  src/Search/Search.tsx
  src/View/View.tsx
  src/helpers/apiCalls.tsx
Labels: API, component

#22 Feature/jcs/api to app
  package-lock.json
  package.json
  src/Home/Home.scss
  src/Home/Home.tsx
  src/View/View.scss
  src/helpers/topCities.ts
Labels: UX, component

#23 Feature/map
  src/About/About.scss
  src/About/About.test.tsx
  src/About/About.tsx
  src/App/App.scss
  src/Header/Header.scss
  src/Header/Header.tsx
  src/Location/Location.tsx
  src/Search/Search.scss
  src/View/View-test.tsx
  src/View/View.scss
  src/View/View.test.tsx
  src/View/View.tsx
  src/assets/ap3.jpg
  src/index.css
  src/styles/_variables.scss
Labels: UX, component, testing

#24 Feature/styling
  src/About/About.scss
  src/About/About.tsx
  src/App/App.test.tsx
  src/Header/Header.scss
  src/Home/Home.scss
  src/Home/Home.test.tsx
  src/Home/Home.tsx
  src/Location/Location.scss
  src/Location/Location.test.tsx
  src/Location/Location.tsx
  src/Search/Search.scss
  src/Search/Search.test.tsx
  src/Search/Search.tsx
  src/View/View.scss
  src/View/View.tsx
  src/assets/50d.png
  src/assets/bee.png
  src/assets/eye.png
  src/assets/liquid.png
  src/assets/lungs.png
  src/assets/search.png
  src/assets/sun.png
  src/assets/water-drop.png
  src/assets/wind.png
  src/styles/_variables.scss
Labels: UX, component, testing

#31 Feature/jcs/refactor
  public/index.html
  src/App/App.scss
  src/App/App.test.tsx
  src/App/App.tsx
  src/Card/Card.scss
  src/Card/Card.test.tsx
  src/Card/Card.tsx
  src/Header/Header.tsx
  src/Home/Home.scss
  src/Home/Home.tsx
  src/Search/Search.tsx
  src/View/View-test.tsx
  src/View/View.scss
  src/View/View.tsx
  src/helpers/airData.ts
  src/helpers/apiCalls.tsx
  src/helpers/cities.ts
Labels: API

#34 Feature/home
  public/america.png
  public/globe.png
  public/index.html
  src/About/About.scss
  src/About/About.tsx
  src/App/App.scss
  src/App/App.tsx
  src/Card/Card.scss
  src/Card/Card.tsx
  src/Header/Header.scss
  src/Header/Header.tsx
  src/Home/Home.scss
  src/Home/Home.tsx
  src/Results/Results.scss
  src/Results/Results.tsx
  src/Search/Search.scss
  src/assets/altitude.jpg
  src/assets/america.png
  src/assets/beach.jpg
  src/assets/covid.png
  src/assets/roadTrip.jpeg
  src/assets/wildfire.jpg
  src/helpers/cities.ts
  src/styles/_variables.scss
Labels: UX

#37 Refactor/results
  src/About/About.tsx
  src/App/App.tsx
  src/Home/Home.tsx
  src/Results/Results.tsx
  src/Search/Search.tsx
Labels: bug, enhancement

#38 Testing/results
  jest.config.js
  package-lock.json
  package.json
  src/About/About.test.tsx
  src/App/App.test.tsx
  src/Home/Home.test.tsx
  src/Results/Results.test.tsx
  src/Search/Search.test.tsx
  src/jest.config.js
Labels: API, testing

#49 Feature/display result
  src/App/App.tsx
  src/Location/Location.tsx
  src/Results/Results.tsx
  src/helpers/apiCalls.tsx
  src/helpers/dataCleaner.tsx
Labels: API, component, enhancement

#47 Feature/jcs location comp
  src/App/App.tsx
  src/Home/Home.scss
  src/Location/Location.tsx
  src/Search/Search.test.tsx
  src/helpers/locationProps.ts
Labels: bug, component, enhancement

#50 Feature/fecth home
  src/About/About.tsx
  src/App/App.tsx
  src/Card/Card.scss
  src/Card/Card.tsx
  src/Home/Home.scss
  src/Home/Home.tsx
  src/Location/Location.tsx
  src/Search/Search.scss
  src/helpers/apiCalls.tsx
  src/helpers/cities.ts
  src/styles/_variables.scss
Labels: API, bug, component

#60 Feature/jcs location comp
  src/App/App.tsx
  src/Location/Location.tsx
  src/WeeklyData/WeeklyData.tsx
  src/WeeklyForecast/WeeklyForecast.scss
  src/WeeklyForecast/WeeklyForecast.test.tsx
  src/WeeklyForecast/WeeklyForecast.tsx
  src/helpers/conversions.ts
  src/styles/_variables.scss
Labels: component, enhancement

#61 Feature/style details
  src/App/App.scss
  src/App/App.tsx
  src/Card/Card.scss
  src/Card/Card.tsx
  src/Header/Header.scss
  src/Header/Header.tsx
  src/Home/Home.scss
  src/Home/Home.tsx
  src/Location/Location.scss
  src/Location/Location.tsx
  src/Results/Results.scss
  src/Results/Results.tsx
  src/Search/Search.scss
  src/WeeklyForecast/WeeklyForecast.scss
  src/WeeklyForecast/WeeklyForecast.tsx
  src/assets/11n.png
  src/helpers/dataFilter.tsx
  src/helpers/detailsdefinitions.ts
Labels: API, UX, bug, component

#68 Feature/jcs timedate func
  src/Card/Card.tsx
  src/Location/Location.tsx
  src/WeeklyForecast/WeeklyForecast.tsx
  src/helpers/apiCalls.tsx
  src/helpers/conversions.ts
  src/helpers/conversions.tsx
  src/helpers/detailsdefinitions.ts
Labels: bug, component, enhancement

#71 Testing/app
  src/App/App.test.tsx
Labels: testing

#72 Feature/cleanUp
  src/About/About.scss
  src/About/About.test.tsx
  src/About/About.tsx
  src/Card/Card.scss
  src/Card/Card.tsx
  src/Home/Home.scss
  src/Location/Location.scss
  src/Location/Location.tsx
  src/WeeklyForecast/WeeklyForecast.scss
  src/WeeklyForecast/WeeklyForecast.tsx
  src/assets/cough.png
  src/assets/forest-fire.png
  src/assets/notepad.png
  src/helpers/apiCalls.tsx
  src/helpers/conversions.tsx
  src/helpers/dataFilter.tsx
  src/styles/_variables.scss
Labels: API, UX, component, testing

#76 Testing/results and home
  src/App/App.test.tsx
  src/Card/Card.test.tsx
  src/Home/Home.test.tsx
  src/Results/Results.test.tsx
  src/Results/Results.tsx
Labels: testing

#85 Feature/jcs testing refactor
  src/App/App.tsx
  src/Home/Home.tsx
  src/Location/Location.scss
  src/Location/Location.tsx
  src/WeeklyForecast/WeeklyForecast.tsx
  src/helpers/apiCalls.tsx
  src/helpers/conversions.test.tsx
  src/helpers/conversions.tsx
  src/helpers/detailsdefinitions.ts
  src/helpers/typeDefinitions.ts
Labels: bug, testing

#86 Feature/location and tests
  .github/README.md
  .github/README_TEMPLATE.md
  src/About/About.tsx
  src/Card/Card.scss
  src/Card/Card.tsx
  src/Home/Home.scss
  src/Home/Home.tsx
  src/Location/Location.scss
  src/Location/Location.test.tsx
  src/Location/Location.tsx
  src/WeeklyForecast/WeeklyForecast.scss
  src/WeeklyForecast/WeeklyForecast.test.tsx
  src/WeeklyForecast/WeeklyForecast.tsx
  src/assets/greenbackpack.png
  src/assets/greensoccer.png
  src/assets/greenwalking.png
  src/assets/orangebackpack.png
  src/assets/orangesoccer.png
  src/assets/orangewalking.png
  src/assets/redbackpack.png
  src/assets/redsoccer.png
  src/assets/redwalking.png
  src/helpers/conversions.tsx
  src/helpers/dataFilter.tsx
  src/helpers/typeDefinitions.ts
Labels: UX, bug, component, documentation, testing

#87 Testing/review all
  src/App/App.tsx
  src/Home/Home.test.tsx
  src/Home/Home.tsx
  src/helpers/typeDefinitions.ts
Labels: testing

#88 Feature/jcs testing
  src/App/App.test.tsx
  src/Location/Location.test.tsx
  src/Location/Location.tsx
  src/helpers/conversions.test.tsx
Labels: testing
